4-4 slightly resized, screen orientation is taken into account in som…
vrg18/surf-flutter pull request #12
Opened 2020-12-10 05:23 UTC by vrg18

1. "... используйте ConstrainedBox ... Почему размер текста поменялся?"

Обернул так:
              child: ConstrainedBox(
                constraints: BoxConstraints(maxWidth: 150),
                child: Text(
                  sight.nameSight,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                  style: SIGHT_CARD_TITLE_STYLE,
                ),
              ),
Текст стал ширинорй 150, т.к. мы ему "спустили" дополнительное ограничение maxWidth: 150

2-4.
![изображение](https://user-images.githubusercontent.com/49246223/101725067-57c07400-3ac9-11eb-8d5b-e6eb89eaa444.png)

2020-12-10 14:49 UTC, artem-zaitsev requested changes
Ответтьте на вопросы и поправьте нейминг.

Замечания по неймингу уже делались в другом ПР(правда там немного ошися ревьюер с названием, но по форме указал правильно).

camelCase - для любых переменных/полей/функций
PascalCase(вроде так) - для классов
snake_case - для файлов

2020-12-10 14:49 UTC, artem-zaitsev commented on lib/ui/res/colors.dart
>  const Color secondary_text_color = Color(0xFF3B3E5B);
используйте camelCase. Для именования цевтов/ресурсов/констант тоже.

2020-12-10 14:49 UTC, artem-zaitsev commented on lib/ui/screen/sight_card.dart
> +              style: SIGHT_CARD_CATEGORY_STYLE,
camelCase

2020-12-10 14:49 UTC, artem-zaitsev commented on lib/ui/screen/sight_list_screen.dart
> +    var portrait = MediaQuery.of(context).orientation == Orientation.portrait;
Если хотите поработать с ориентацией экрана, то проще использовать OrientationBuilder

2020-12-10 14:49 UTC, artem-zaitsev commented on lib/ui/screen/sight_detail.dart
> +          flex: 19,
Почему именно 19?

2020-12-10 14:49 UTC, artem-zaitsev commented on lib/ui/screen/sight_detail.dart
> +          flex: 19,
и про другие значения flex тот же вопрос.

2020-12-10 17:03 UTC, vrg18 commented on lib/ui/res/colors.dart
>  const Color secondary_text_color = Color(0xFF3B3E5B);
Сделал

2020-12-10 17:04 UTC, vrg18 commented on lib/ui/screen/sight_card.dart
> +              style: SIGHT_CARD_CATEGORY_STYLE,
Сделал

2020-12-10 17:25 UTC, vrg18 commented on lib/ui/screen/sight_list_screen.dart
> +    var portrait = MediaQuery.of(context).orientation == Orientation.portrait;
Сделал с помощью OrientationBuilder

2020-12-10 18:20 UTC, vrg18 commented on lib/ui/screen/sight_detail.dart
> +          flex: 19,
Истинная декларативная вёрстка, imho  -  поменьше размеров в условных пикселях (разве лишь всяческие отступы), побольше долей (Expanded/flex) и AspectRatio. Поэтому сделал на Expanded. Понимаю, что такое решение на годится для горизонтального режима, но для него потом хотел сделать дополнительную верстку. 19 и другие значения - просто подогнал к макету в Figma. Зачтите, pls, этот урок (он ведь не про Expanded, да и на выходные никак невозможно остаться без нового урока) и напишите, надо ли переделать с Expanded/flex на что-то другое. Если не надо, добавлю горизонтальную верстку для этого экрана. В обоих случаях сдам вместе со следующим ДЗ.

2020-12-11 07:05 UTC, vrg18 commented on lib/ui/screen/sight_detail.dart
> +          flex: 19,
Все таки решил сверстать дополнительный горизонтальный SightDetail. Imho, теперь стало элегантнее, по прежнему на Expanded/flex, но нет теперь странных цифр типа "flex: 19".

![изображение](https://user-images.githubusercontent.com/49246223/101873590-a3921c80-3ba0-11eb-87ff-332c3d956bf0.png)

![изображение](https://user-images.githubusercontent.com/49246223/101873673-ce7c7080-3ba0-11eb-9dc7-3ea8577cf03a.png)

2020-12-11 13:47 UTC, artem-zaitsev commented on lib/ui/screen/sight_detail.dart
> +          flex: 19,
Тут скорее вбросил для того, чтобы было меньше "магических чисел". Если они берутся из головы и не прокомментированы, значит забудутся или другой член команды не будет знать об их смысле. А это приведет к очень болезненным багам.

Просто совет: если уж пишите числа, которые нигде не фигурируют, то либо комментарий , либо как константу с осмысленным названием.

2020-12-11 13:48 UTC, artem-zaitsev approved these changes

2020-12-11 16:33 UTC, vrg18 commented on lib/ui/screen/sight_detail.dart
> +          flex: 19,
Принято, спасибо.

2020-12-11 16:33 UTC, merged