4-6 added top and bottom tabs
vrg18/surf-flutter pull request #14
Opened 2020-12-16 05:26 UTC by vrg18

На экране Избранное верхний Tabs работает в том числе и по свайпу

![изображение](https://user-images.githubusercontent.com/49246223/102308528-3f949d00-3f80-11eb-9022-dd631a91669e.png)
![изображение](https://user-images.githubusercontent.com/49246223/102308591-6521a680-3f80-11eb-8b98-df299b188722.png)
![изображение](https://user-images.githubusercontent.com/49246223/102308676-9d28e980-3f80-11eb-83a8-6ee3ace0a086.png)

2020-12-16 14:23 UTC, artem-zaitsev requested changes
Поправьте комментарии

2020-12-16 14:23 UTC, artem-zaitsev commented on lib/domain/sight.dart
> +  String name;
Совет: эти поля по сути final.
Да и в принципе, полезно делать их иммутабельными и изменять через копирование. (за редким исключением). Это может показаться плохо с точки зрения перфоманса, но зачастую клиенты тонкие и перфоманс непроседает.

Естественно, там где нагрузка высокая этот совет работать не будет.

2020-12-16 14:23 UTC, artem-zaitsev commented on lib/ui/screen/bottom_bar.dart
> +class BottomBar extends StatefulWidget {
Документация. После этого урока без документированных классов не будем ставить зачет.

2020-12-16 14:23 UTC, artem-zaitsev commented on lib/ui/screen/bottom_bar.dart
> +  static List<Widget> _widgetOptions = <Widget>[
Чем обусловлено приватное статическое поле?

2020-12-16 14:23 UTC, artem-zaitsev commented on lib/ui/screen/bottom_bar.dart
> +    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(statusBarColor: Colors.transparent));
лучше не в билд, а например в initState. Иначе выполняете эту операцию на каждое нажатие кнопки.

2020-12-16 14:23 UTC, artem-zaitsev commented on lib/ui/screen/bottom_bar.dart
> +class BottomBar extends StatefulWidget {
Вот кстати косяк с неймингом: по названию класса - это просто плашка с кнопками.
По факту - это целиком экран(даже два).

По этому не пущу даже сейчас с таким неймингом.

2020-12-16 14:23 UTC, artem-zaitsev commented on lib/ui/screen/bottom_bar.dart
> +  static List<Widget> _widgetOptions = <Widget>[
это по сути просто final

2020-12-16 14:23 UTC, artem-zaitsev commented on lib/ui/screen/favorites.dart
> +class Favorites extends StatefulWidget {
док

2020-12-16 14:23 UTC, artem-zaitsev commented on lib/ui/screen/favorites.dart
> +          preferredSize: Size.fromHeight(40),
40 лучше вынести в константу. Иначе при изменении высоты будете в двух местах менять.

2020-12-16 14:23 UTC, artem-zaitsev commented on lib/ui/screen/select_slider_tab.dart
> +class SelectSliderTabs extends StatelessWidget {
док

2020-12-16 14:23 UTC, artem-zaitsev commented on lib/ui/screen/favorites.dart
> +                    ? [
кажется более простым способом было бы внести проверку внутрь onPanUpdate()

2020-12-16 17:06 UTC, vrg18 commented on lib/domain/sight.dart
> +  String name;
Ок, исправил

2020-12-16 17:06 UTC, vrg18 commented on lib/ui/screen/bottom_bar.dart
> +class BottomBar extends StatefulWidget {
Исправил

2020-12-16 17:09 UTC, vrg18 commented on lib/ui/screen/bottom_bar.dart
> +  static List<Widget> _widgetOptions = <Widget>[
Да, неправ. Проштудирую еще раз эту часть Dart

2020-12-16 17:10 UTC, vrg18 commented on lib/ui/screen/bottom_bar.dart
> +    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(statusBarColor: Colors.transparent));
Перенес

2020-12-16 17:10 UTC, vrg18 commented on lib/ui/screen/favorites.dart
> +class Favorites extends StatefulWidget {
Ок

2020-12-16 17:10 UTC, vrg18 commented on lib/ui/screen/favorites.dart
> +          preferredSize: Size.fromHeight(40),
Сделал

2020-12-16 17:10 UTC, vrg18 commented on lib/ui/screen/select_slider_tab.dart
> +class SelectSliderTabs extends StatelessWidget {
Ок

2020-12-16 17:10 UTC, vrg18 commented on lib/ui/screen/favorites.dart
> +                    ? [
Поправил

2020-12-17 11:14 UTC, Jokerkras approved these changes

2020-12-17 11:14 UTC, Jokerkras commented on lib/ui/res/sizes.dart
> +/// Определения размеров, применяемых в приложении. Коды цветов взяты из Figma
Лишнее предложение скопировали)

2020-12-17 11:14 UTC, Jokerkras commented on lib/ui/screen/favorites.dart
> +      appBar: AppBar(
сделайте лучше папку в screen - favorites и уже там сделайте папку с виджетами, которые используются на этом экране. Так например точно стоило бы перенести туда AppBar, так как он занимает довольно много места, тем более опыт создания кастомного Аппбара у вас уже есть.

2020-12-17 11:14 UTC, Jokerkras commented on lib/ui/screen/favorites.dart
> +          GridView.extent(
два child у вас отличаются только входными данными, можно было бы вынести создание одного child в функцию, и передавать в нее только список элементов для отрисовки

2020-12-17 11:14 UTC, Jokerkras commented on lib/ui/screen/favorites.dart
> +              borderRadius: BorderRadius.all(Radius.circular(sliderHeightOnScreenFavorites / 2)),
Уверен, что эта строка не умещается в 80 символов, которые считаются стандартной длинной строки в IDE, не забывайте про trailing comma и автоформатирование в IDE,
margin: EdgeInsets.symmetric(horizontal: basicBorderSize, vertical: basicBorderSize), - тоже выглядит довольно громоздко, можно поставить запятую после basicBorderSize

2020-12-17 13:51 UTC, vrg18 commented on lib/ui/screen/favorites.dart
> +      appBar: AppBar(
Сделал

2020-12-17 13:52 UTC, vrg18 commented on lib/ui/screen/favorites.dart
> +          GridView.extent(
Сделал

2020-12-17 14:03 UTC, vrg18 commented on lib/ui/screen/favorites.dart
> +              borderRadius: BorderRadius.all(Radius.circular(sliderHeightOnScreenFavorites / 2)),
У меня в IDE стоит 120, imho оптимальная ширина для современных широких экранов. В проектах, в которых довелось участвовать, обычно было 120, а в одном даже 180.
Про trailing comma помню, использую. Данную строку
borderRadius: BorderRadius.all(Radius.circular(sliderHeightOnScreenFavorites / 2)),
посчитал неразбитую с помощью trailing comma более читабельной. Если аргументов более чем один обычно разбиваю trailing comma.

2020-12-17 14:08 UTC, Jokerkras commented on lib/ui/screen/favorites.dart
> +              borderRadius: BorderRadius.all(Radius.circular(sliderHeightOnScreenFavorites / 2)),
Хорошо, длина оправдана)
А trailing comma помагает не только в форматировании, но и в понимании иерархии

2020-12-17 14:29 UTC, vrg18 commented on lib/ui/screen/favorites.dart
> +              borderRadius: BorderRadius.all(Radius.circular(sliderHeightOnScreenFavorites / 2)),
Да, согласен. Все-таки, учитывая что на 120 сошлись, и вышеназванная строка влезает, надо ли ее разбить по вертикали с помощью trailing comma?

2020-12-17 14:31 UTC, Jokerkras commented on lib/ui/screen/favorites.dart
> +              borderRadius: BorderRadius.all(Radius.circular(sliderHeightOnScreenFavorites / 2)),
Давайте пока так остановимся, возьмем как правило 2+ => trailing comma

2020-12-17 17:38 UTC, merged